version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_URL:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
      CLERK_SECRET_KEY:
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /
      NEXT_PUBLIC_TINY_EDITOR_API_KEY:
      NEXT_CLERK_WEBHOOK_SECRET: whsec_erJXNtiEmSyU6XyobojZnp7fA2otaDtD
      MONGODB_URL:
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000/
      OPENAI_API_KEY:
      NEXT_PUBLIC_GOOGLE_GIMINI_API_KEY:
